import type { PostgresExplainPlanNode } from "./types";

export const sampleExplainPlan: PostgresExplainPlanNode = {
  nodeType: "Nested Loop",
  startupCost: 0.85,
  totalCost: 1842.55,
  planRows: 500,
  actualRows: 1200,
  actualStartupTime: 0.12,
  actualTotalTime: 92.4,
  sharedHitBlocks: 8020,
  sharedReadBlocks: 414,
  tempReadBlocks: 0,
  tempWrittenBlocks: 0,
  children: [
    {
      nodeType: "Index Scan",
      relationName: "customers",
      indexName: "idx_customers_status",
      startupCost: 0.42,
      totalCost: 240.1,
      planRows: 300,
      actualRows: 310,
      actualStartupTime: 0.04,
      actualTotalTime: 8.6,
      sharedHitBlocks: 180,
      sharedReadBlocks: 12,
      children: [],
    },
    {
      nodeType: "Seq Scan",
      relationName: "orders",
      startupCost: 0,
      totalCost: 5.28,
      planRows: 4,
      actualRows: 4,
      actualStartupTime: 0.02,
      actualTotalTime: 0.18,
      sharedHitBlocks: 7840,
      sharedReadBlocks: 402,
      children: [],
    },
  ],
};
