import type { KnowledgeTopic } from "./types";
import { knowledgeTopicSchema } from "./types";

const allDialects = [
  "postgresql",
  "mysql",
  "oracle",
  "sqlite",
  "sqlserver",
  "generic",
] as const;

const makeExamples = (keyword: string) => ({
  syntax: `${keyword} ...`,
  basicExample: `SELECT id, name\nFROM customers\nWHERE status = 'active';`,
  advancedExample: `WITH recent_orders AS (\n  SELECT customer_id, COUNT(*) AS orders_count\n  FROM orders\n  WHERE created_at >= CURRENT_DATE - INTERVAL '30 days'\n  GROUP BY customer_id\n)\nSELECT c.id, c.email, r.orders_count\nFROM customers c\nJOIN recent_orders r ON r.customer_id = c.id;`,
});

const parsedKnowledgeTopics = knowledgeTopicSchema
  .array()
  .parse([
    {
      id: "select-basics",
      slug: "select-basics",
      category: "basics",
      difficulty: "beginner",
      dialects: allDialects,
      relatedTopics: ["where-filtering", "unbounded-result-set"],
      relatedRules: ["select-star", "unbounded-select"],
      translations: {
        en: {
          title: "SELECT basics",
          shortDescription: "Choose precise columns and shape tabular results.",
          explanation:
            "SELECT defines the projection returned by a query. Production queries should name the columns they need instead of relying on SELECT *.",
          ...makeExamples("SELECT column_list FROM table"),
          commonMistakes: ["Using SELECT * in application paths.", "Returning columns that the caller never reads."],
          performanceTips: ["Narrow projections reduce IO.", "Explicit columns make covering indexes easier to use."],
        },
        pl: {
          title: "Podstawy SELECT",
          shortDescription: "Wybieraj precyzyjne kolumny i ksztaltuj wynik tabelaryczny.",
          explanation:
            "SELECT definiuje projekcje zwracana przez zapytanie. Zapytania produkcyjne powinny wymieniac potrzebne kolumny zamiast polegac na SELECT *.",
          ...makeExamples("SELECT lista_kolumn FROM tabela"),
          commonMistakes: ["Uzywanie SELECT * w sciezkach aplikacji.", "Zwracanie kolumn, ktorych odbiorca nie czyta."],
          performanceTips: ["Wezsze projekcje zmniejszaja IO.", "Jawne kolumny ulatwiaja uzycie indeksow pokrywajacych."],
        },
      },
    },
    {
      id: "where-filtering",
      slug: "where-filtering",
      category: "basics",
      difficulty: "beginner",
      dialects: allDialects,
      relatedTopics: ["index-basics", "null-semantics"],
      relatedRules: ["too-many-or-conditions", "implicit-conversion-risk"],
      translations: {
        en: {
          title: "WHERE filtering",
          shortDescription: "Limit rows with predicates that match the data model.",
          explanation:
            "WHERE predicates determine which rows qualify. Good filters are selective, type-correct, and written so indexes remain usable.",
          ...makeExamples("WHERE predicate"),
          commonMistakes: ["Filtering numeric columns with string literals.", "Wrapping indexed columns in functions without a matching index."],
          performanceTips: ["Prefer selective predicates early in query design.", "Keep data types aligned to avoid implicit casts."],
        },
        pl: {
          title: "Filtrowanie WHERE",
          shortDescription: "Ograniczaj wiersze predykatami pasujacymi do modelu danych.",
          explanation:
            "Predykaty WHERE decyduja, ktore wiersze kwalifikuja sie do wyniku. Dobre filtry sa selektywne, poprawne typowo i pozwalaja uzyc indeksow.",
          ...makeExamples("WHERE predykat"),
          commonMistakes: ["Filtrowanie kolumn liczbowych literałami tekstowymi.", "Opakowywanie indeksowanych kolumn funkcjami bez pasujacego indeksu."],
          performanceTips: ["Projektuj zapytanie wokol selektywnych predykatow.", "Pilnuj zgodnosci typow, aby unikac rzutowan."],
        },
      },
    },
    {
      id: "order-by",
      slug: "order-by",
      category: "basics",
      difficulty: "beginner",
      dialects: allDialects,
      relatedTopics: ["pagination-offset-vs-keyset", "composite-indexes"],
      relatedRules: ["order-by-without-limit", "order-by-random"],
      translations: {
        en: {
          title: "ORDER BY",
          shortDescription: "Return rows in deterministic order.",
          explanation:
            "ORDER BY is the only reliable way to request row order. Sorting large sets can be expensive unless the order matches an index.",
          syntax: "ORDER BY column [ASC|DESC]",
          basicExample: "SELECT id, created_at\nFROM orders\nORDER BY created_at DESC\nLIMIT 50;",
          advancedExample: "SELECT id, created_at\nFROM orders\nWHERE created_at < :cursor\nORDER BY created_at DESC, id DESC\nLIMIT 50;",
          commonMistakes: ["Assuming natural table order is stable.", "Sorting a large result without LIMIT."],
          performanceTips: ["Match ORDER BY columns to an index.", "Use a deterministic tie-breaker for pagination."],
        },
        pl: {
          title: "ORDER BY",
          shortDescription: "Zwracaj wiersze w deterministycznej kolejnosci.",
          explanation:
            "ORDER BY to jedyny pewny sposob zdefiniowania kolejnosci. Sortowanie duzych zbiorow bywa kosztowne, jesli porzadek nie pasuje do indeksu.",
          syntax: "ORDER BY kolumna [ASC|DESC]",
          basicExample: "SELECT id, created_at\nFROM orders\nORDER BY created_at DESC\nLIMIT 50;",
          advancedExample: "SELECT id, created_at\nFROM orders\nWHERE created_at < :cursor\nORDER BY created_at DESC, id DESC\nLIMIT 50;",
          commonMistakes: ["Zakladanie stabilnego naturalnego porzadku tabeli.", "Sortowanie duzego wyniku bez LIMIT."],
          performanceTips: ["Dopasuj ORDER BY do indeksu.", "Dodaj deterministyczny tie-breaker przy paginacji."],
        },
      },
    },
    {
      id: "limit-fetch-top",
      slug: "limit-fetch-top",
      category: "dialects",
      difficulty: "beginner",
      dialects: allDialects,
      relatedTopics: ["order-by", "pagination-offset-vs-keyset"],
      relatedRules: ["order-by-without-limit", "unbounded-select"],
      translations: {
        en: {
          title: "LIMIT / FETCH / TOP",
          shortDescription: "Limit result size across SQL dialects.",
          explanation:
            "Different engines use different syntax to cap result sets, but the intent is the same: avoid returning unbounded rows.",
          syntax: "PostgreSQL/MySQL/SQLite: LIMIT n\nSQL Server: TOP n\nOracle/standard: FETCH FIRST n ROWS ONLY",
          basicExample: "SELECT id\nFROM products\nORDER BY created_at DESC\nLIMIT 20;",
          advancedExample: "SELECT id\nFROM products\nORDER BY created_at DESC\nFETCH FIRST 20 ROWS ONLY;",
          commonMistakes: ["Using LIMIT without ORDER BY for user-facing pages.", "Expecting TOP to work in every dialect."],
          performanceTips: ["Pair limits with selective filters.", "Use indexes that support the requested order."],
        },
        pl: {
          title: "LIMIT / FETCH / TOP",
          shortDescription: "Ograniczaj rozmiar wyniku w roznych dialektach SQL.",
          explanation:
            "Silniki maja rozna skladnie ograniczania wyniku, ale cel jest ten sam: unikac nieograniczonych odczytow.",
          syntax: "PostgreSQL/MySQL/SQLite: LIMIT n\nSQL Server: TOP n\nOracle/standard: FETCH FIRST n ROWS ONLY",
          basicExample: "SELECT id\nFROM products\nORDER BY created_at DESC\nLIMIT 20;",
          advancedExample: "SELECT id\nFROM products\nORDER BY created_at DESC\nFETCH FIRST 20 ROWS ONLY;",
          commonMistakes: ["Uzywanie LIMIT bez ORDER BY dla stron uzytkownika.", "Zakladanie, ze TOP dziala w kazdym dialekcie."],
          performanceTips: ["Lacz limity z selektywnymi filtrami.", "Uzywaj indeksow wspierajacych zadany porzadek."],
        },
      },
    },
    {
      id: "join-fundamentals",
      slug: "join-fundamentals",
      category: "joins",
      difficulty: "beginner",
      dialects: allDialects,
      relatedTopics: ["inner-join-vs-left-join", "foreign-keys"],
      relatedRules: ["missing-join-condition", "cross-join"],
      translations: {
        en: {
          title: "JOIN fundamentals",
          shortDescription: "Combine related tables through explicit predicates.",
          explanation:
            "JOIN connects rows from multiple tables. The ON predicate should express the relationship and should usually be backed by indexes.",
          syntax: "FROM left_table l JOIN right_table r ON r.left_id = l.id",
          basicExample: "SELECT o.id, c.email\nFROM orders o\nJOIN customers c ON c.id = o.customer_id;",
          advancedExample: "SELECT c.id, COUNT(o.id) AS orders_count\nFROM customers c\nLEFT JOIN orders o ON o.customer_id = c.id\nGROUP BY c.id;",
          commonMistakes: ["Forgetting ON predicates.", "Using comma joins in new code."],
          performanceTips: ["Index foreign-key columns used in joins.", "Check join order and row estimates with EXPLAIN."],
        },
        pl: {
          title: "Podstawy JOIN",
          shortDescription: "Lacz powiazane tabele przez jawne predykaty.",
          explanation:
            "JOIN laczy wiersze z wielu tabel. Predykat ON powinien opisywac relacje i zwykle powinien byc wsparty indeksami.",
          syntax: "FROM tabela_l l JOIN tabela_p r ON r.left_id = l.id",
          basicExample: "SELECT o.id, c.email\nFROM orders o\nJOIN customers c ON c.id = o.customer_id;",
          advancedExample: "SELECT c.id, COUNT(o.id) AS orders_count\nFROM customers c\nLEFT JOIN orders o ON o.customer_id = c.id\nGROUP BY c.id;",
          commonMistakes: ["Pomijanie predykatow ON.", "Uzywanie comma joinow w nowym kodzie."],
          performanceTips: ["Indeksuj kolumny kluczy obcych uzywane w JOIN.", "Sprawdzaj kolejnosc JOIN i estymacje przez EXPLAIN."],
        },
      },
    },
    {
      id: "inner-join-vs-left-join",
      slug: "inner-join-vs-left-join",
      category: "joins",
      difficulty: "beginner",
      dialects: allDialects,
      relatedTopics: ["join-fundamentals", "null-semantics"],
      relatedRules: ["missing-join-condition"],
      translations: {
        en: {
          title: "INNER JOIN vs LEFT JOIN",
          shortDescription: "Choose whether unmatched left rows should remain.",
          explanation:
            "INNER JOIN returns only matching rows. LEFT JOIN keeps rows from the left side and fills right-side columns with NULL when no match exists.",
          syntax: "INNER JOIN ... ON ...\nLEFT JOIN ... ON ...",
          basicExample: "SELECT c.id, o.id AS order_id\nFROM customers c\nLEFT JOIN orders o ON o.customer_id = c.id;",
          advancedExample: "SELECT c.id\nFROM customers c\nLEFT JOIN orders o ON o.customer_id = c.id\nWHERE o.id IS NULL;",
          commonMistakes: ["Adding WHERE predicates on the right table that turn LEFT JOIN into INNER JOIN.", "Using LEFT JOIN when a match is required."],
          performanceTips: ["Filter right-side rows inside ON when preserving left rows matters.", "Index both sides of frequent join keys."],
        },
        pl: {
          title: "INNER JOIN vs LEFT JOIN",
          shortDescription: "Wybierz, czy wiersze bez dopasowania po lewej maja zostac.",
          explanation:
            "INNER JOIN zwraca tylko dopasowane wiersze. LEFT JOIN zachowuje lewa strone i wypelnia prawa strone NULL, gdy nie ma dopasowania.",
          syntax: "INNER JOIN ... ON ...\nLEFT JOIN ... ON ...",
          basicExample: "SELECT c.id, o.id AS order_id\nFROM customers c\nLEFT JOIN orders o ON o.customer_id = c.id;",
          advancedExample: "SELECT c.id\nFROM customers c\nLEFT JOIN orders o ON o.customer_id = c.id\nWHERE o.id IS NULL;",
          commonMistakes: ["Dodawanie WHERE na prawej tabeli, co zmienia LEFT JOIN w INNER JOIN.", "Uzywanie LEFT JOIN, gdy dopasowanie jest wymagane."],
          performanceTips: ["Filtry prawej strony dawaj do ON, gdy chcesz zachowac lewa strone.", "Indeksuj obie strony czestych kluczy JOIN."],
        },
      },
    },
    {
      id: "group-by",
      slug: "group-by",
      category: "aggregation",
      difficulty: "beginner",
      dialects: allDialects,
      relatedTopics: ["having", "window-functions"],
      relatedRules: ["group-by-many-columns", "distinct-overuse"],
      translations: {
        en: {
          title: "GROUP BY",
          shortDescription: "Aggregate rows into groups.",
          explanation:
            "GROUP BY creates one result row per grouping key. It is useful for counts, sums, and summaries, but can become expensive with high-cardinality keys.",
          syntax: "SELECT key, aggregate(value) FROM table GROUP BY key",
          basicExample: "SELECT customer_id, COUNT(*)\nFROM orders\nGROUP BY customer_id;",
          advancedExample: "SELECT customer_id, date_trunc('month', created_at) AS month, SUM(total)\nFROM orders\nGROUP BY customer_id, month;",
          commonMistakes: ["Grouping by columns that are not needed.", "Using DISTINCT to paper over incorrect joins."],
          performanceTips: ["Pre-filter before grouping.", "Consider indexes on grouping and filtering columns."],
        },
        pl: {
          title: "GROUP BY",
          shortDescription: "Agreguj wiersze w grupy.",
          explanation:
            "GROUP BY tworzy jeden wiersz wyniku na klucz grupowania. Przydaje sie do zliczen i sum, ale bywa kosztowny przy wysokiej kardynalnosci.",
          syntax: "SELECT klucz, agregat(wartosc) FROM tabela GROUP BY klucz",
          basicExample: "SELECT customer_id, COUNT(*)\nFROM orders\nGROUP BY customer_id;",
          advancedExample: "SELECT customer_id, date_trunc('month', created_at) AS month, SUM(total)\nFROM orders\nGROUP BY customer_id, month;",
          commonMistakes: ["Grupowanie po niepotrzebnych kolumnach.", "Uzywanie DISTINCT do ukrywania blednych JOIN."],
          performanceTips: ["Filtruj przed grupowaniem.", "Rozwaz indeksy na kolumnach filtrowania i grupowania."],
        },
      },
    },
    {
      id: "having",
      slug: "having",
      category: "aggregation",
      difficulty: "beginner",
      dialects: allDialects,
      relatedTopics: ["group-by", "where-filtering"],
      relatedRules: [],
      translations: {
        en: {
          title: "HAVING",
          shortDescription: "Filter groups after aggregation.",
          explanation:
            "HAVING filters aggregated groups. Row-level conditions should stay in WHERE so the database can reduce data before aggregation.",
          syntax: "GROUP BY key HAVING aggregate(value) > threshold",
          basicExample: "SELECT customer_id, COUNT(*) AS order_count\nFROM orders\nGROUP BY customer_id\nHAVING COUNT(*) > 5;",
          advancedExample: "SELECT customer_id, SUM(total) AS revenue\nFROM orders\nWHERE status = 'paid'\nGROUP BY customer_id\nHAVING SUM(total) > 1000;",
          commonMistakes: ["Putting row-level filters in HAVING.", "Repeating expensive expressions unnecessarily."],
          performanceTips: ["Use WHERE before HAVING when possible.", "Aggregate only the rows needed for the result."],
        },
        pl: {
          title: "HAVING",
          shortDescription: "Filtruj grupy po agregacji.",
          explanation:
            "HAVING filtruje zagregowane grupy. Warunki poziomu wiersza powinny zostac w WHERE, aby baza zmniejszyla dane przed agregacja.",
          syntax: "GROUP BY klucz HAVING agregat(wartosc) > prog",
          basicExample: "SELECT customer_id, COUNT(*) AS order_count\nFROM orders\nGROUP BY customer_id\nHAVING COUNT(*) > 5;",
          advancedExample: "SELECT customer_id, SUM(total) AS revenue\nFROM orders\nWHERE status = 'paid'\nGROUP BY customer_id\nHAVING SUM(total) > 1000;",
          commonMistakes: ["Wkladanie filtrow wierszy do HAVING.", "Niepotrzebne powtarzanie kosztownych wyrazen."],
          performanceTips: ["Uzywaj WHERE przed HAVING, gdy to mozliwe.", "Agreguj tylko wiersze potrzebne do wyniku."],
        },
      },
    },
    {
      id: "subqueries",
      slug: "subqueries",
      category: "basics",
      difficulty: "intermediate",
      dialects: allDialects,
      relatedTopics: ["cte", "not-in-null-risk"],
      relatedRules: ["not-in-null-risk", "nullable-not-in"],
      translations: {
        en: {
          title: "Subqueries",
          shortDescription: "Nest one query inside another.",
          explanation:
            "Subqueries can express existence checks, derived tables, and scalar values. Their performance depends on correlation, indexes, and optimizer support.",
          syntax: "WHERE EXISTS (SELECT 1 FROM other WHERE ...)",
          basicExample: "SELECT id\nFROM customers c\nWHERE EXISTS (SELECT 1 FROM orders o WHERE o.customer_id = c.id);",
          advancedExample: "SELECT c.id, recent.order_count\nFROM customers c\nJOIN (SELECT customer_id, COUNT(*) AS order_count FROM orders GROUP BY customer_id) recent ON recent.customer_id = c.id;",
          commonMistakes: ["Using NOT IN when NULLs are possible.", "Writing correlated subqueries that execute too often."],
          performanceTips: ["Prefer EXISTS for existence checks.", "Index columns used inside correlated predicates."],
        },
        pl: {
          title: "Podzapytania",
          shortDescription: "Zagniezdzaj jedno zapytanie w drugim.",
          explanation:
            "Podzapytania wyrazaja sprawdzenia istnienia, tabele pochodne i wartosci skalarne. Wydajnosc zalezy od korelacji, indeksow i optymalizatora.",
          syntax: "WHERE EXISTS (SELECT 1 FROM inna WHERE ...)",
          basicExample: "SELECT id\nFROM customers c\nWHERE EXISTS (SELECT 1 FROM orders o WHERE o.customer_id = c.id);",
          advancedExample: "SELECT c.id, recent.order_count\nFROM customers c\nJOIN (SELECT customer_id, COUNT(*) AS order_count FROM orders GROUP BY customer_id) recent ON recent.customer_id = c.id;",
          commonMistakes: ["Uzywanie NOT IN, gdy mozliwe sa NULL.", "Pisanie skorelowanych podzapytan wykonywanych zbyt czesto."],
          performanceTips: ["Preferuj EXISTS do sprawdzen istnienia.", "Indeksuj kolumny w predykatach skorelowanych."],
        },
      },
    },
    {
      id: "cte",
      slug: "cte",
      category: "basics",
      difficulty: "intermediate",
      dialects: ["postgresql", "mysql", "oracle", "sqlite", "sqlserver", "generic"],
      relatedTopics: ["subqueries", "query-optimization-basics"],
      relatedRules: [],
      translations: {
        en: {
          title: "CTE",
          shortDescription: "Name query steps with WITH clauses.",
          explanation:
            "Common table expressions make complex queries easier to read. Optimizer behavior differs by engine, so materialization details matter.",
          syntax: "WITH name AS (SELECT ...) SELECT ... FROM name",
          basicExample: "WITH paid_orders AS (SELECT * FROM orders WHERE status = 'paid')\nSELECT COUNT(*) FROM paid_orders;",
          advancedExample: "WITH monthly AS (SELECT date_trunc('month', created_at) AS month, SUM(total) revenue FROM orders GROUP BY month)\nSELECT month, revenue FROM monthly ORDER BY month;",
          commonMistakes: ["Assuming every CTE is materialized.", "Using CTEs to hide unbounded scans."],
          performanceTips: ["Check plans when a CTE is reused.", "Use CTEs to clarify, then verify execution shape."],
        },
        pl: {
          title: "CTE",
          shortDescription: "Nazywaj kroki zapytania klauzula WITH.",
          explanation:
            "Common table expressions poprawiaja czytelnosc zlozonych zapytan. Zachowanie optymalizatora rozni sie miedzy silnikami.",
          syntax: "WITH nazwa AS (SELECT ...) SELECT ... FROM nazwa",
          basicExample: "WITH paid_orders AS (SELECT * FROM orders WHERE status = 'paid')\nSELECT COUNT(*) FROM paid_orders;",
          advancedExample: "WITH monthly AS (SELECT date_trunc('month', created_at) AS month, SUM(total) revenue FROM orders GROUP BY month)\nSELECT month, revenue FROM monthly ORDER BY month;",
          commonMistakes: ["Zakladanie, ze kazde CTE jest materializowane.", "Ukrywanie nieograniczonych skanow w CTE."],
          performanceTips: ["Sprawdzaj plany, gdy CTE jest uzyte wielokrotnie.", "Uzywaj CTE dla czytelnosci i weryfikuj plan."],
        },
      },
    },
    {
      id: "window-functions",
      slug: "window-functions",
      category: "aggregation",
      difficulty: "advanced",
      dialects: allDialects,
      relatedTopics: ["group-by", "order-by"],
      relatedRules: [],
      translations: {
        en: {
          title: "Window functions",
          shortDescription: "Calculate values across related rows without collapsing them.",
          explanation:
            "Window functions use OVER to compute ranks, running totals, and partitioned metrics while keeping row-level detail.",
          syntax: "function() OVER (PARTITION BY key ORDER BY sort_key)",
          basicExample: "SELECT id, customer_id, ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY created_at DESC) AS rn\nFROM orders;",
          advancedExample: "SELECT id, total, SUM(total) OVER (PARTITION BY customer_id ORDER BY created_at) AS running_total\nFROM orders;",
          commonMistakes: ["Confusing GROUP BY with window partitions.", "Omitting ORDER BY for order-sensitive functions."],
          performanceTips: ["Index partition and order columns for large windows.", "Limit input rows before windowing when possible."],
        },
        pl: {
          title: "Funkcje okna",
          shortDescription: "Licz wartosci na powiazanych wierszach bez ich zwijania.",
          explanation:
            "Funkcje okna uzywaja OVER do rang, sum narastajacych i metryk po partycjach przy zachowaniu detalu wierszy.",
          syntax: "funkcja() OVER (PARTITION BY klucz ORDER BY sort_key)",
          basicExample: "SELECT id, customer_id, ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY created_at DESC) AS rn\nFROM orders;",
          advancedExample: "SELECT id, total, SUM(total) OVER (PARTITION BY customer_id ORDER BY created_at) AS running_total\nFROM orders;",
          commonMistakes: ["Mylenie GROUP BY z partycjami okna.", "Pomijanie ORDER BY dla funkcji wrazliwych na kolejnosc."],
          performanceTips: ["Indeksuj kolumny partycji i sortowania dla duzych okien.", "Ogranicz wejscie przed funkcjami okna, gdy mozliwe."],
        },
      },
    },
    {
      id: "index-basics",
      slug: "index-basics",
      category: "indexes",
      difficulty: "beginner",
      dialects: allDialects,
      relatedTopics: ["composite-indexes", "sequential-scan-vs-index-scan"],
      relatedRules: ["function-in-where", "leading-wildcard-like"],
      translations: {
        en: {
          title: "Index basics",
          shortDescription: "Understand how indexes help reads and affect writes.",
          explanation:
            "Indexes provide alternate access paths to table data. They can speed up SELECT queries but add storage and write maintenance cost.",
          syntax: "CREATE INDEX index_name ON table_name (column_name);",
          basicExample: "CREATE INDEX idx_orders_customer_id ON orders (customer_id);",
          advancedExample: "CREATE INDEX idx_orders_customer_created ON orders (customer_id, created_at DESC);",
          commonMistakes: ["Indexing every column.", "Forgetting write and storage cost."],
          performanceTips: ["Index selective predicates and join keys.", "Verify impact with EXPLAIN ANALYZE."],
        },
        pl: {
          title: "Podstawy indeksow",
          shortDescription: "Zrozum, jak indeksy pomagaja odczytom i wplywaja na zapisy.",
          explanation:
            "Indeksy daja alternatywne sciezki dostepu do danych. Moga przyspieszac SELECT, ale kosztuja miejsce i utrzymanie przy zapisach.",
          syntax: "CREATE INDEX nazwa_indeksu ON nazwa_tabeli (kolumna);",
          basicExample: "CREATE INDEX idx_orders_customer_id ON orders (customer_id);",
          advancedExample: "CREATE INDEX idx_orders_customer_created ON orders (customer_id, created_at DESC);",
          commonMistakes: ["Indeksowanie kazdej kolumny.", "Pomijanie kosztu zapisow i miejsca."],
          performanceTips: ["Indeksuj selektywne predykaty i klucze JOIN.", "Weryfikuj wplyw przez EXPLAIN ANALYZE."],
        },
      },
    },
    {
      id: "composite-indexes",
      slug: "composite-indexes",
      category: "indexes",
      difficulty: "intermediate",
      dialects: allDialects,
      relatedTopics: ["index-basics", "order-by"],
      relatedRules: [],
      translations: {
        en: {
          title: "Composite indexes",
          shortDescription: "Index multiple columns in a useful order.",
          explanation:
            "Composite indexes are ordered by column sequence. The leading columns matter most for filtering and sorting.",
          syntax: "CREATE INDEX idx ON table_name (col1, col2);",
          basicExample: "CREATE INDEX idx_orders_customer_status ON orders (customer_id, status);",
          advancedExample: "CREATE INDEX idx_orders_customer_created ON orders (customer_id, created_at DESC, id DESC);",
          commonMistakes: ["Putting low-selectivity columns first without reason.", "Creating overlapping indexes that duplicate each other."],
          performanceTips: ["Order columns by equality filters, then range and sort columns.", "Consolidate redundant indexes."],
        },
        pl: {
          title: "Indeksy zlozone",
          shortDescription: "Indeksuj wiele kolumn w uzytecznej kolejnosci.",
          explanation:
            "Indeksy zlozone sa uporzadkowane wedlug sekwencji kolumn. Kolumny poczatkowe sa najwazniejsze dla filtrow i sortowania.",
          syntax: "CREATE INDEX idx ON tabela (kol1, kol2);",
          basicExample: "CREATE INDEX idx_orders_customer_status ON orders (customer_id, status);",
          advancedExample: "CREATE INDEX idx_orders_customer_created ON orders (customer_id, created_at DESC, id DESC);",
          commonMistakes: ["Dawanie malo selektywnych kolumn na poczatek bez powodu.", "Tworzenie nakladajacych sie indeksow."],
          performanceTips: ["Ukladaj kolumny: rownosci, potem zakresy i sortowanie.", "Usuwaj redundantne indeksy po weryfikacji."],
        },
      },
    },
    {
      id: "functional-indexes",
      slug: "functional-indexes",
      category: "indexes",
      difficulty: "intermediate",
      dialects: ["postgresql", "oracle", "sqlite", "mysql", "generic"],
      relatedTopics: ["where-filtering", "index-basics"],
      relatedRules: ["function-in-where"],
      translations: {
        en: {
          title: "Functional indexes",
          shortDescription: "Index an expression such as LOWER(email).",
          explanation:
            "Functional indexes can support predicates that apply a function to a column, as long as the query expression matches the index expression.",
          syntax: "CREATE INDEX idx ON table_name (LOWER(column_name));",
          basicExample: "CREATE INDEX idx_users_lower_email ON users (LOWER(email));",
          advancedExample: "SELECT id FROM users WHERE LOWER(email) = LOWER(:email);",
          commonMistakes: ["Creating an expression index that does not match the query.", "Using functions when normalized data would be simpler."],
          performanceTips: ["Use functional indexes for stable, frequently searched expressions.", "Check dialect-specific expression index support."],
        },
        pl: {
          title: "Indeksy funkcyjne",
          shortDescription: "Indeksuj wyrazenie, np. LOWER(email).",
          explanation:
            "Indeksy funkcyjne wspieraja predykaty nakladajace funkcje na kolumne, jesli wyrazenie zapytania pasuje do wyrazenia indeksu.",
          syntax: "CREATE INDEX idx ON tabela (LOWER(kolumna));",
          basicExample: "CREATE INDEX idx_users_lower_email ON users (LOWER(email));",
          advancedExample: "SELECT id FROM users WHERE LOWER(email) = LOWER(:email);",
          commonMistakes: ["Tworzenie indeksu wyrazeniowego niepasujacego do zapytania.", "Uzywanie funkcji, gdy prostsza bylaby normalizacja danych."],
          performanceTips: ["Stosuj dla stabilnych, czesto wyszukiwanych wyrazen.", "Sprawdz wsparcie dialektu dla indeksow wyrazeniowych."],
        },
      },
    },
    {
      id: "covering-indexes",
      slug: "covering-indexes",
      category: "indexes",
      difficulty: "intermediate",
      dialects: ["postgresql", "mysql", "sqlserver", "sqlite", "generic"],
      relatedTopics: ["select-basics", "composite-indexes"],
      relatedRules: ["select-star"],
      translations: {
        en: {
          title: "Covering indexes",
          shortDescription: "Serve a query from an index without reading the table.",
          explanation:
            "A covering index contains the columns needed for filtering and output. Support differs by engine, but the principle is reducing table lookups.",
          syntax: "CREATE INDEX idx ON table_name (filter_col) INCLUDE (output_col);",
          basicExample: "CREATE INDEX idx_orders_status_include_total ON orders (status) INCLUDE (total);",
          advancedExample: "SELECT total FROM orders WHERE status = 'paid';",
          commonMistakes: ["Trying to cover SELECT *.", "Adding too many included columns."],
          performanceTips: ["Keep covered projections narrow.", "Use INCLUDE columns where supported."],
        },
        pl: {
          title: "Indeksy pokrywajace",
          shortDescription: "Obsluguj zapytanie z indeksu bez czytania tabeli.",
          explanation:
            "Indeks pokrywajacy zawiera kolumny potrzebne do filtrowania i wyniku. Wsparcie rozni sie miedzy silnikami, ale cel to mniej odczytow tabeli.",
          syntax: "CREATE INDEX idx ON tabela (kol_filtra) INCLUDE (kol_wyniku);",
          basicExample: "CREATE INDEX idx_orders_status_include_total ON orders (status) INCLUDE (total);",
          advancedExample: "SELECT total FROM orders WHERE status = 'paid';",
          commonMistakes: ["Proba pokrycia SELECT *.", "Dodawanie zbyt wielu kolumn INCLUDE."],
          performanceTips: ["Utrzymuj waska projekcje.", "Uzywaj INCLUDE tam, gdzie dialekt wspiera."],
        },
      },
    },
    {
      id: "primary-keys",
      slug: "primary-keys",
      category: "basics",
      difficulty: "beginner",
      dialects: allDialects,
      relatedTopics: ["foreign-keys", "index-basics"],
      relatedRules: [],
      translations: {
        en: {
          title: "Primary keys",
          shortDescription: "Identify rows with stable unique values.",
          explanation:
            "A primary key enforces uniqueness and not-null semantics. Most databases automatically back it with an index.",
          syntax: "PRIMARY KEY (id)",
          basicExample: "CREATE TABLE customers (id BIGINT PRIMARY KEY, email TEXT NOT NULL);",
          advancedExample: "CREATE TABLE order_items (order_id BIGINT, line_no INT, PRIMARY KEY (order_id, line_no));",
          commonMistakes: ["Using mutable business data as a key.", "Skipping primary keys in operational tables."],
          performanceTips: ["Keep primary keys stable and compact.", "Understand clustering effects in engines that cluster by primary key."],
        },
        pl: {
          title: "Klucze glowne",
          shortDescription: "Identyfikuj wiersze stabilnymi unikalnymi wartosciami.",
          explanation:
            "Klucz glowny wymusza unikalnosc i brak NULL. Wiekszosc baz automatycznie podpiera go indeksem.",
          syntax: "PRIMARY KEY (id)",
          basicExample: "CREATE TABLE customers (id BIGINT PRIMARY KEY, email TEXT NOT NULL);",
          advancedExample: "CREATE TABLE order_items (order_id BIGINT, line_no INT, PRIMARY KEY (order_id, line_no));",
          commonMistakes: ["Uzywanie zmiennych danych biznesowych jako klucza.", "Pomijanie kluczy glownych w tabelach operacyjnych."],
          performanceTips: ["Utrzymuj klucze stabilne i kompaktowe.", "Zrozum clustering w silnikach klastrujacych po PK."],
        },
      },
    },
    {
      id: "foreign-keys",
      slug: "foreign-keys",
      category: "joins",
      difficulty: "beginner",
      dialects: allDialects,
      relatedTopics: ["primary-keys", "join-fundamentals"],
      relatedRules: [],
      translations: {
        en: {
          title: "Foreign keys",
          shortDescription: "Represent relationships and protect referential integrity.",
          explanation:
            "Foreign keys connect child rows to parent rows. They protect correctness and often define join paths.",
          syntax: "FOREIGN KEY (customer_id) REFERENCES customers(id)",
          basicExample: "ALTER TABLE orders ADD CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES customers(id);",
          advancedExample: "CREATE INDEX idx_orders_customer_id ON orders (customer_id);",
          commonMistakes: ["Forgetting indexes on child foreign-key columns.", "Disabling constraints without compensating checks."],
          performanceTips: ["Index foreign keys used in joins.", "Consider cascade behavior carefully."],
        },
        pl: {
          title: "Klucze obce",
          shortDescription: "Reprezentuj relacje i chron integralnosc referencyjna.",
          explanation:
            "Klucze obce lacza wiersze dziecka z rodzicem. Chronia poprawność i czesto wyznaczaja sciezki JOIN.",
          syntax: "FOREIGN KEY (customer_id) REFERENCES customers(id)",
          basicExample: "ALTER TABLE orders ADD CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES customers(id);",
          advancedExample: "CREATE INDEX idx_orders_customer_id ON orders (customer_id);",
          commonMistakes: ["Brak indeksow na kolumnach kluczy obcych dziecka.", "Wylaczanie ograniczen bez innych kontroli."],
          performanceTips: ["Indeksuj klucze obce uzywane w JOIN.", "Ostroznie projektuj zachowanie kaskadowe."],
        },
      },
    },
    {
      id: "constraints",
      slug: "constraints",
      category: "basics",
      difficulty: "beginner",
      dialects: allDialects,
      relatedTopics: ["primary-keys", "foreign-keys"],
      relatedRules: [],
      translations: {
        en: {
          title: "Constraints",
          shortDescription: "Move data rules into the database.",
          explanation:
            "Constraints enforce not-null, uniqueness, checks, and relationships. They keep data valid even when multiple applications write to it.",
          syntax: "NOT NULL | UNIQUE | CHECK (...) | FOREIGN KEY (...)",
          basicExample: "CREATE TABLE users (email TEXT NOT NULL UNIQUE, age INT CHECK (age >= 0));",
          advancedExample: "ALTER TABLE payments ADD CONSTRAINT positive_amount CHECK (amount > 0);",
          commonMistakes: ["Relying only on application validation.", "Writing vague constraints that do not model real rules."],
          performanceTips: ["Unique constraints create useful indexes.", "Validated constraints help optimizers reason about data."],
        },
        pl: {
          title: "Ograniczenia",
          shortDescription: "Przenos reguly danych do bazy.",
          explanation:
            "Constraints wymuszaja NOT NULL, unikalnosc, CHECK i relacje. Utrzymuja poprawne dane nawet przy wielu aplikacjach zapisujacych do bazy.",
          syntax: "NOT NULL | UNIQUE | CHECK (...) | FOREIGN KEY (...)",
          basicExample: "CREATE TABLE users (email TEXT NOT NULL UNIQUE, age INT CHECK (age >= 0));",
          advancedExample: "ALTER TABLE payments ADD CONSTRAINT positive_amount CHECK (amount > 0);",
          commonMistakes: ["Poleganie tylko na walidacji aplikacji.", "Pisanie ograniczen nieoddajacych realnych regul."],
          performanceTips: ["Unikalne ograniczenia tworza przydatne indeksy.", "Zweryfikowane constraints pomagaja optymalizatorowi."],
        },
      },
    },
    {
      id: "transactions",
      slug: "transactions",
      category: "transactions",
      difficulty: "beginner",
      dialects: allDialects,
      relatedTopics: ["acid", "unsafe-updates"],
      relatedRules: ["update-without-where", "delete-without-where", "unsafe-drop-table"],
      translations: {
        en: {
          title: "Transactions",
          shortDescription: "Group changes into atomic units of work.",
          explanation:
            "Transactions let multiple statements succeed or fail together. They are essential around risky updates, deletes, and migrations.",
          syntax: "BEGIN; ... COMMIT; -- or ROLLBACK;",
          basicExample: "BEGIN;\nUPDATE accounts SET balance = balance - 100 WHERE id = 1;\nUPDATE accounts SET balance = balance + 100 WHERE id = 2;\nCOMMIT;",
          advancedExample: "BEGIN;\nSELECT id FROM orders WHERE id = :id FOR UPDATE;\nUPDATE orders SET status = 'paid' WHERE id = :id;\nCOMMIT;",
          commonMistakes: ["Running destructive changes outside a transaction.", "Holding transactions open while waiting on external work."],
          performanceTips: ["Keep transactions short.", "Use appropriate isolation for the business invariant."],
        },
        pl: {
          title: "Transakcje",
          shortDescription: "Grupuj zmiany w atomowe jednostki pracy.",
          explanation:
            "Transakcje pozwalaja wielu instrukcjom zakonczyc sie wspolnie sukcesem albo porazka. Sa kluczowe przy ryzykownych UPDATE, DELETE i migracjach.",
          syntax: "BEGIN; ... COMMIT; -- albo ROLLBACK;",
          basicExample: "BEGIN;\nUPDATE accounts SET balance = balance - 100 WHERE id = 1;\nUPDATE accounts SET balance = balance + 100 WHERE id = 2;\nCOMMIT;",
          advancedExample: "BEGIN;\nSELECT id FROM orders WHERE id = :id FOR UPDATE;\nUPDATE orders SET status = 'paid' WHERE id = :id;\nCOMMIT;",
          commonMistakes: ["Uruchamianie destrukcyjnych zmian poza transakcja.", "Trzymanie transakcji podczas pracy zewnetrznej."],
          performanceTips: ["Utrzymuj transakcje krotkie.", "Dobieraj izolacje do reguly biznesowej."],
        },
      },
    },
    {
      id: "acid",
      slug: "acid",
      category: "transactions",
      difficulty: "intermediate",
      dialects: allDialects,
      relatedTopics: ["transactions", "constraints"],
      relatedRules: [],
      translations: {
        en: {
          title: "ACID",
          shortDescription: "The core guarantees behind transactional databases.",
          explanation:
            "ACID stands for atomicity, consistency, isolation, and durability. Understanding the tradeoffs helps design correct write paths.",
          syntax: "Atomicity + Consistency + Isolation + Durability",
          basicExample: "BEGIN;\n-- all writes succeed together\nCOMMIT;",
          advancedExample: "SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;\nBEGIN;\nSELECT ...;\nCOMMIT;",
          commonMistakes: ["Assuming every isolation level prevents every anomaly.", "Ignoring durability and backup requirements."],
          performanceTips: ["Use the weakest isolation that preserves correctness.", "Measure contention when raising isolation."],
        },
        pl: {
          title: "ACID",
          shortDescription: "Glowne gwarancje baz transakcyjnych.",
          explanation:
            "ACID oznacza atomicity, consistency, isolation i durability. Zrozumienie kompromisow pomaga projektowac poprawne zapisy.",
          syntax: "Atomicity + Consistency + Isolation + Durability",
          basicExample: "BEGIN;\n-- wszystkie zapisy udaja sie razem\nCOMMIT;",
          advancedExample: "SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;\nBEGIN;\nSELECT ...;\nCOMMIT;",
          commonMistakes: ["Zakladanie, ze kazdy poziom izolacji blokuje kazda anomalie.", "Ignorowanie trwalosci i backupow."],
          performanceTips: ["Uzywaj najslabszej izolacji zachowujacej poprawnosc.", "Mierz kontencje przy wyzszej izolacji."],
        },
      },
    },
    {
      id: "explain-basics",
      slug: "explain-basics",
      category: "explain",
      difficulty: "beginner",
      dialects: allDialects,
      relatedTopics: ["sequential-scan-vs-index-scan", "execution-plan-costs"],
      relatedRules: [],
      translations: {
        en: {
          title: "EXPLAIN basics",
          shortDescription: "Read the database plan before guessing.",
          explanation:
            "EXPLAIN shows how a database plans to execute a query. EXPLAIN ANALYZE runs it and adds actual timing and rows.",
          syntax: "EXPLAIN [ANALYZE] SELECT ...",
          basicExample: "EXPLAIN SELECT * FROM orders WHERE customer_id = 42;",
          advancedExample: "EXPLAIN (ANALYZE, BUFFERS) SELECT * FROM orders WHERE customer_id = 42;",
          commonMistakes: ["Optimizing without a plan.", "Comparing estimated rows only when actual data is needed."],
          performanceTips: ["Use ANALYZE in safe environments.", "Look for row estimate errors and expensive nodes."],
        },
        pl: {
          title: "Podstawy EXPLAIN",
          shortDescription: "Czytaj plan bazy zamiast zgadywac.",
          explanation:
            "EXPLAIN pokazuje, jak baza planuje wykonac zapytanie. EXPLAIN ANALYZE uruchamia je i dodaje realny czas oraz wiersze.",
          syntax: "EXPLAIN [ANALYZE] SELECT ...",
          basicExample: "EXPLAIN SELECT * FROM orders WHERE customer_id = 42;",
          advancedExample: "EXPLAIN (ANALYZE, BUFFERS) SELECT * FROM orders WHERE customer_id = 42;",
          commonMistakes: ["Optymalizacja bez planu.", "Porownywanie tylko estymacji, gdy potrzebne sa realne dane."],
          performanceTips: ["Uzywaj ANALYZE w bezpiecznych srodowiskach.", "Szukaj bledow estymacji i drogich wezlow."],
        },
      },
    },
    {
      id: "sequential-scan-vs-index-scan",
      slug: "sequential-scan-vs-index-scan",
      category: "explain",
      difficulty: "intermediate",
      dialects: allDialects,
      relatedTopics: ["index-basics", "explain-basics"],
      relatedRules: [],
      translations: {
        en: {
          title: "Sequential scan vs index scan",
          shortDescription: "Know when scanning is normal and when an index should help.",
          explanation:
            "A sequential scan reads many table pages. An index scan follows an index to locate rows. The best choice depends on selectivity and cost.",
          syntax: "Seq Scan | Index Scan | Index Only Scan",
          basicExample: "EXPLAIN SELECT * FROM orders WHERE customer_id = 42;",
          advancedExample: "EXPLAIN (ANALYZE, BUFFERS) SELECT id FROM orders WHERE customer_id = 42;",
          commonMistakes: ["Assuming every sequential scan is bad.", "Expecting an index on low-cardinality data to always help."],
          performanceTips: ["Check selectivity and table size.", "Use index-only scans with narrow projections when possible."],
        },
        pl: {
          title: "Sequential scan vs index scan",
          shortDescription: "Wiedz, kiedy skan jest normalny, a kiedy indeks powinien pomoc.",
          explanation:
            "Sequential scan czyta wiele stron tabeli. Index scan idzie po indeksie do wierszy. Najlepszy wybor zalezy od selektywnosci i kosztu.",
          syntax: "Seq Scan | Index Scan | Index Only Scan",
          basicExample: "EXPLAIN SELECT * FROM orders WHERE customer_id = 42;",
          advancedExample: "EXPLAIN (ANALYZE, BUFFERS) SELECT id FROM orders WHERE customer_id = 42;",
          commonMistakes: ["Zakladanie, ze kazdy sequential scan jest zly.", "Oczekiwanie, ze indeks na niskiej kardynalnosci zawsze pomoze."],
          performanceTips: ["Sprawdz selektywnosc i rozmiar tabeli.", "Uzywaj index-only scan z waska projekcja, gdy mozliwe."],
        },
      },
    },
    {
      id: "query-optimization-basics",
      slug: "query-optimization-basics",
      category: "performance",
      difficulty: "intermediate",
      dialects: allDialects,
      relatedTopics: ["explain-basics", "index-basics"],
      relatedRules: ["leading-wildcard-like", "order-by-random", "too-many-joins"],
      translations: {
        en: {
          title: "Query optimization basics",
          shortDescription: "Optimize with evidence, not guesswork.",
          explanation:
            "Optimization starts with the workload, data distribution, and execution plan. Rewrite queries and indexes only after identifying the bottleneck.",
          syntax: "Measure -> inspect plan -> change one thing -> measure again",
          basicExample: "EXPLAIN (ANALYZE, BUFFERS) SELECT ...;",
          advancedExample: "CREATE INDEX CONCURRENTLY idx_orders_customer_created ON orders (customer_id, created_at DESC);",
          commonMistakes: ["Adding indexes without measuring.", "Optimizing queries that are not on a real hot path."],
          performanceTips: ["Use production-like data.", "Compare before and after plans."],
        },
        pl: {
          title: "Podstawy optymalizacji zapytan",
          shortDescription: "Optymalizuj na podstawie dowodow, nie zgadywania.",
          explanation:
            "Optymalizacja zaczyna sie od workloadu, rozkladu danych i planu wykonania. Przepisuj zapytania i indeksy po znalezieniu waskiego gardla.",
          syntax: "Zmierz -> sprawdz plan -> zmien jedna rzecz -> zmierz ponownie",
          basicExample: "EXPLAIN (ANALYZE, BUFFERS) SELECT ...;",
          advancedExample: "CREATE INDEX CONCURRENTLY idx_orders_customer_created ON orders (customer_id, created_at DESC);",
          commonMistakes: ["Dodawanie indeksow bez pomiaru.", "Optymalizacja zapytan spoza realnej goracej sciezki."],
          performanceTips: ["Uzywaj danych podobnych do produkcji.", "Porownuj plany przed i po."],
        },
      },
    },
    {
      id: "pagination-offset-vs-keyset",
      slug: "pagination-offset-vs-keyset",
      category: "performance",
      difficulty: "intermediate",
      dialects: allDialects,
      relatedTopics: ["order-by", "composite-indexes"],
      relatedRules: ["offset-pagination"],
      translations: {
        en: {
          title: "Pagination: OFFSET vs keyset",
          shortDescription: "Avoid deep OFFSET scans with cursor-based pagination.",
          explanation:
            "OFFSET is simple but gets slower on deep pages because skipped rows still have to be found. Keyset pagination uses the last seen value.",
          syntax: "WHERE sort_key < :cursor ORDER BY sort_key DESC LIMIT n",
          basicExample: "SELECT id FROM orders ORDER BY created_at DESC LIMIT 50 OFFSET 5000;",
          advancedExample: "SELECT id FROM orders WHERE created_at < :cursor ORDER BY created_at DESC LIMIT 50;",
          commonMistakes: ["Using OFFSET for infinite scroll.", "Missing a stable tie-breaker column."],
          performanceTips: ["Use keyset pagination for deep browsing.", "Index cursor and order columns together."],
        },
        pl: {
          title: "Paginacja: OFFSET vs keyset",
          shortDescription: "Unikaj glebokich skanow OFFSET przez paginacje kursorowa.",
          explanation:
            "OFFSET jest prosty, ale wolnieje na glebokich stronach, bo pominiete wiersze nadal trzeba znalezc. Keyset uzywa ostatniej widzianej wartosci.",
          syntax: "WHERE sort_key < :cursor ORDER BY sort_key DESC LIMIT n",
          basicExample: "SELECT id FROM orders ORDER BY created_at DESC LIMIT 50 OFFSET 5000;",
          advancedExample: "SELECT id FROM orders WHERE created_at < :cursor ORDER BY created_at DESC LIMIT 50;",
          commonMistakes: ["Uzywanie OFFSET dla infinite scroll.", "Brak stabilnej kolumny rozstrzygajacej remisy."],
          performanceTips: ["Uzywaj keyset dla glebokiego przegladania.", "Indeksuj razem kolumny kursora i sortowania."],
        },
      },
    },
    {
      id: "sql-antipatterns-overview",
      slug: "sql-antipatterns-overview",
      category: "antipatterns",
      difficulty: "beginner",
      dialects: allDialects,
      relatedTopics: ["query-optimization-basics", "transactions"],
      relatedRules: ["select-star", "delete-without-where", "update-without-where"],
      translations: {
        en: {
          title: "SQL anti-patterns overview",
          shortDescription: "Recognize query shapes that often cause trouble.",
          explanation:
            "Anti-patterns are not always bugs, but they deserve review because they often indicate missing constraints, missing indexes, or unsafe workflows.",
          syntax: "Bad shape -> reason -> safer alternative",
          basicExample: "SELECT * FROM events;",
          advancedExample: "DELETE FROM sessions; -- dangerous without WHERE",
          commonMistakes: ["Treating every warning as automatic failure.", "Ignoring repeated warnings in hot paths."],
          performanceTips: ["Prioritize rules that hit frequent queries.", "Pair rule findings with real plans."],
        },
        pl: {
          title: "Przeglad antywzorcow SQL",
          shortDescription: "Rozpoznawaj ksztalty zapytan, ktore czesto powoduja problemy.",
          explanation:
            "Antywzorce nie zawsze sa bledami, ale wymagaja przegladu, bo czesto wskazuja brak constraints, indeksow albo bezpiecznego procesu.",
          syntax: "Zly ksztalt -> powod -> bezpieczniejsza alternatywa",
          basicExample: "SELECT * FROM events;",
          advancedExample: "DELETE FROM sessions; -- niebezpieczne bez WHERE",
          commonMistakes: ["Traktowanie kazdego ostrzezenia jako automatycznej porazki.", "Ignorowanie powtarzalnych ostrzezen w goracych sciezkach."],
          performanceTips: ["Priorytetyzuj reguly dotyczace czestych zapytan.", "Lacz wyniki regul z realnymi planami."],
        },
      },
    },
    {
      id: "dialect-differences",
      slug: "dialect-differences",
      category: "dialects",
      difficulty: "intermediate",
      dialects: allDialects,
      relatedTopics: ["limit-fetch-top", "upsert-patterns"],
      relatedRules: ["implicit-conversion-risk"],
      translations: {
        en: {
          title: "Dialect differences",
          shortDescription: "Understand syntax and behavior across SQL engines.",
          explanation:
            "SQL is standardized, but real engines differ in pagination, date functions, JSON syntax, upserts, booleans, and optimizer features.",
          syntax: "Same concept, dialect-specific syntax",
          basicExample: "PostgreSQL: SELECT NOW();\nSQL Server: SELECT GETDATE();",
          advancedExample: "PostgreSQL: INSERT ... ON CONFLICT DO UPDATE\nMySQL: INSERT ... ON DUPLICATE KEY UPDATE",
          commonMistakes: ["Copying syntax between engines without checking semantics.", "Assuming identical NULL or boolean behavior."],
          performanceTips: ["Use dialect-specific features deliberately.", "Document portability boundaries."],
        },
        pl: {
          title: "Roznice dialektow",
          shortDescription: "Rozum skladnie i zachowanie roznych silnikow SQL.",
          explanation:
            "SQL ma standard, ale silniki roznia sie paginacja, funkcjami dat, JSON, upsertami, booleanami i optymalizatorem.",
          syntax: "To samo pojecie, skladnia konkretnego dialektu",
          basicExample: "PostgreSQL: SELECT NOW();\nSQL Server: SELECT GETDATE();",
          advancedExample: "PostgreSQL: INSERT ... ON CONFLICT DO UPDATE\nMySQL: INSERT ... ON DUPLICATE KEY UPDATE",
          commonMistakes: ["Kopiowanie skladni miedzy silnikami bez semantyki.", "Zakladanie identycznego NULL lub boolean."],
          performanceTips: ["Uzywaj cech dialektu swiadomie.", "Dokumentuj granice przenosnosci."],
        },
      },
    },
    {
      id: "full-text-search-performance",
      slug: "full-text-search-performance",
      category: "performance",
      difficulty: "intermediate",
      dialects: ["postgresql", "mysql", "sqlserver", "sqlite", "generic"],
      relatedTopics: ["leading-wildcard-search", "functional-indexes"],
      relatedRules: ["leading-wildcard-like"],
      translations: {
        en: {
          title: "Full-text search performance",
          shortDescription: "Use search-specific indexes for contains queries.",
          explanation:
            "Contains searches rarely fit normal B-tree indexes. Full-text, trigram, or external search systems can match the access pattern better.",
          syntax: "Use engine-specific full-text or trigram indexes",
          basicExample: "SELECT id FROM articles WHERE title LIKE '%database%';",
          advancedExample: "CREATE INDEX idx_articles_title_trgm ON articles USING gin (title gin_trgm_ops);",
          commonMistakes: ["Expecting LIKE '%term' to use a normal index.", "Using full-text search for exact identifiers."],
          performanceTips: ["Choose search technology by query semantics.", "Measure index size and update cost."],
        },
        pl: {
          title: "Wydajnosc full-text search",
          shortDescription: "Uzywaj indeksow wyszukiwawczych dla zapytan contains.",
          explanation:
            "Wyszukiwania contains rzadko pasuja do zwyklych indeksow B-tree. Full-text, trigramy albo zewnetrzne wyszukiwarki lepiej pasuja do wzorca.",
          syntax: "Uzyj full-text albo trigramow dostepnych w silniku",
          basicExample: "SELECT id FROM articles WHERE title LIKE '%database%';",
          advancedExample: "CREATE INDEX idx_articles_title_trgm ON articles USING gin (title gin_trgm_ops);",
          commonMistakes: ["Oczekiwanie, ze LIKE '%term' uzyje zwyklego indeksu.", "Uzywanie full-text dla dokladnych identyfikatorow."],
          performanceTips: ["Dobierz technologie do semantyki wyszukiwania.", "Mierz rozmiar indeksu i koszt aktualizacji."],
        },
      },
    },
    {
      id: "null-semantics",
      slug: "null-semantics",
      category: "basics",
      difficulty: "intermediate",
      dialects: allDialects,
      relatedTopics: ["where-filtering", "subqueries"],
      relatedRules: ["not-in-null-risk", "nullable-not-in"],
      translations: {
        en: {
          title: "NULL semantics",
          shortDescription: "Handle unknown values explicitly.",
          explanation:
            "NULL means unknown or missing, not an empty value. Comparisons with NULL use three-valued logic and require IS NULL or IS NOT NULL.",
          syntax: "IS NULL | IS NOT NULL | COALESCE(value, fallback)",
          basicExample: "SELECT id FROM users WHERE deleted_at IS NULL;",
          advancedExample: "SELECT id FROM users WHERE NOT EXISTS (SELECT 1 FROM bans b WHERE b.user_id = users.id);",
          commonMistakes: ["Writing column = NULL.", "Using NOT IN when NULL can appear."],
          performanceTips: ["Consider partial indexes for common NULL filters.", "Avoid hiding NULL logic inside unclear expressions."],
        },
        pl: {
          title: "Semantyka NULL",
          shortDescription: "Obsluguj wartosci nieznane jawnie.",
          explanation:
            "NULL oznacza wartosc nieznana lub brakujaca, nie pustke. Porownania z NULL uzywaja logiki trojwartosciowej i wymagaja IS NULL.",
          syntax: "IS NULL | IS NOT NULL | COALESCE(wartosc, fallback)",
          basicExample: "SELECT id FROM users WHERE deleted_at IS NULL;",
          advancedExample: "SELECT id FROM users WHERE NOT EXISTS (SELECT 1 FROM bans b WHERE b.user_id = users.id);",
          commonMistakes: ["Pisanie column = NULL.", "Uzywanie NOT IN, gdy NULL moze wystapic."],
          performanceTips: ["Rozwaz indeksy czesciowe dla czestych filtrow NULL.", "Nie ukrywaj logiki NULL w niejasnych wyrazeniach."],
        },
      },
    },
    {
      id: "upsert-patterns",
      slug: "upsert-patterns",
      category: "dialects",
      difficulty: "intermediate",
      dialects: ["postgresql", "mysql", "sqlite", "sqlserver", "oracle"],
      relatedTopics: ["dialect-differences", "constraints"],
      relatedRules: [],
      translations: {
        en: {
          title: "Upsert patterns",
          shortDescription: "Insert or update safely when a row already exists.",
          explanation:
            "Upsert syntax differs by database, but reliable upserts require a unique key that defines conflict identity.",
          syntax: "INSERT ... ON CONFLICT | ON DUPLICATE KEY | MERGE",
          basicExample: "INSERT INTO users (email, name) VALUES (:email, :name)\nON CONFLICT (email) DO UPDATE SET name = EXCLUDED.name;",
          advancedExample: "MERGE INTO target USING source ON target.id = source.id WHEN MATCHED THEN UPDATE SET ... WHEN NOT MATCHED THEN INSERT ...;",
          commonMistakes: ["Upserting without a unique constraint.", "Using MERGE without understanding concurrency semantics."],
          performanceTips: ["Index the conflict key.", "Measure write amplification on hot keys."],
        },
        pl: {
          title: "Wzorce upsert",
          shortDescription: "Wstawiaj albo aktualizuj bezpiecznie, gdy wiersz juz istnieje.",
          explanation:
            "Skladnia upsert rozni sie miedzy bazami, ale niezawodne upserty wymagaja unikalnego klucza okreslajacego konflikt.",
          syntax: "INSERT ... ON CONFLICT | ON DUPLICATE KEY | MERGE",
          basicExample: "INSERT INTO users (email, name) VALUES (:email, :name)\nON CONFLICT (email) DO UPDATE SET name = EXCLUDED.name;",
          advancedExample: "MERGE INTO target USING source ON target.id = source.id WHEN MATCHED THEN UPDATE SET ... WHEN NOT MATCHED THEN INSERT ...;",
          commonMistakes: ["Upsert bez unikalnego constraint.", "Uzywanie MERGE bez zrozumienia wspolbieznosci."],
          performanceTips: ["Indeksuj klucz konfliktu.", "Mierz write amplification na goracych kluczach."],
        },
      },
    },
    {
      id: "execution-plan-costs",
      slug: "execution-plan-costs",
      category: "explain",
      difficulty: "advanced",
      dialects: allDialects,
      relatedTopics: ["explain-basics", "query-optimization-basics"],
      relatedRules: [],
      translations: {
        en: {
          title: "Execution plan costs",
          shortDescription: "Interpret estimated work and actual runtime carefully.",
          explanation:
            "Plan costs are optimizer estimates, not milliseconds. They help compare alternatives inside one database configuration.",
          syntax: "startup cost .. total cost | estimated rows | actual rows",
          basicExample: "Seq Scan on orders  (cost=0.00..431.00 rows=10000)",
          advancedExample: "Nested Loop  (actual time=0.120..82.410 rows=5000 loops=1)",
          commonMistakes: ["Comparing cost numbers across different engines.", "Ignoring actual rows when estimates are wrong."],
          performanceTips: ["Focus on high total time and bad row estimates.", "Update statistics when estimates drift."],
        },
        pl: {
          title: "Koszty planu wykonania",
          shortDescription: "Ostroznie interpretuj estymowana prace i realny czas.",
          explanation:
            "Koszty planu sa estymacjami optymalizatora, nie milisekundami. Pomagaja porownywac alternatywy w jednej konfiguracji bazy.",
          syntax: "startup cost .. total cost | estimated rows | actual rows",
          basicExample: "Seq Scan on orders  (cost=0.00..431.00 rows=10000)",
          advancedExample: "Nested Loop  (actual time=0.120..82.410 rows=5000 loops=1)",
          commonMistakes: ["Porownywanie kosztow miedzy roznymi silnikami.", "Ignorowanie actual rows przy zlych estymacjach."],
          performanceTips: ["Skup sie na wysokim total time i bledach estymacji.", "Aktualizuj statystyki, gdy estymacje odpływaja."],
        },
      },
    },
    {
      id: "unbounded-result-set",
      slug: "unbounded-result-set",
      category: "performance",
      difficulty: "beginner",
      dialects: allDialects,
      relatedTopics: ["select-basics", "limit-fetch-top"],
      relatedRules: ["unbounded-select", "select-star"],
      translations: {
        en: {
          title: "Unbounded result sets",
          shortDescription: "Avoid queries that can return the whole table by accident.",
          explanation:
            "A query without filters, limits, or aggregation can grow silently as data grows. That risk belongs in review even when the table is small today.",
          syntax: "SELECT columns FROM table WHERE ... LIMIT n",
          basicExample: "SELECT id, email FROM users LIMIT 100;",
          advancedExample: "SELECT id, email FROM users WHERE created_at >= CURRENT_DATE - INTERVAL '7 days' ORDER BY created_at DESC LIMIT 100;",
          commonMistakes: ["Testing on tiny local data and shipping unbounded reads.", "Combining SELECT * with no filter."],
          performanceTips: ["Add production-safe bounds.", "Use pagination or streaming for large exports."],
        },
        pl: {
          title: "Nieograniczone wyniki",
          shortDescription: "Unikaj zapytan, ktore przypadkiem moga zwrocic cala tabele.",
          explanation:
            "Zapytanie bez filtrow, limitow lub agregacji rosnie po cichu razem z danymi. To ryzyko wymaga przegladu nawet przy malej tabeli dzis.",
          syntax: "SELECT kolumny FROM tabela WHERE ... LIMIT n",
          basicExample: "SELECT id, email FROM users LIMIT 100;",
          advancedExample: "SELECT id, email FROM users WHERE created_at >= CURRENT_DATE - INTERVAL '7 days' ORDER BY created_at DESC LIMIT 100;",
          commonMistakes: ["Testowanie na malych danych i wdrazanie nieograniczonych odczytow.", "Laczenie SELECT * z brakiem filtra."],
          performanceTips: ["Dodaj bezpieczne ograniczenia produkcyjne.", "Uzyj paginacji albo streamingu dla duzych eksportow."],
        },
      },
    },
    {
      id: "leading-wildcard-search",
      slug: "leading-wildcard-search",
      category: "performance",
      difficulty: "intermediate",
      dialects: allDialects,
      relatedTopics: ["full-text-search-performance", "index-basics"],
      relatedRules: ["leading-wildcard-like"],
      translations: {
        en: {
          title: "Leading wildcard search",
          shortDescription: "Understand why LIKE '%term' is usually expensive.",
          explanation:
            "A leading wildcard prevents the database from jumping to a prefix in a normal B-tree index. The engine often scans candidates instead.",
          syntax: "LIKE '%term' vs LIKE 'term%'",
          basicExample: "SELECT id FROM products WHERE name LIKE '%phone%';",
          advancedExample: "SELECT id FROM products WHERE name ILIKE 'phone%';",
          commonMistakes: ["Using contains search for autocomplete.", "Adding a normal index and expecting it to fix contains search."],
          performanceTips: ["Use prefix search when the UX allows it.", "Use trigram or full-text indexes for contains search."],
        },
        pl: {
          title: "Wyszukiwanie z wildcardem na poczatku",
          shortDescription: "Zrozum, czemu LIKE '%term' zwykle jest drogie.",
          explanation:
            "Wildcard na poczatku blokuje skok do prefiksu w zwyklym indeksie B-tree. Silnik czesto skanuje kandydatow.",
          syntax: "LIKE '%term' vs LIKE 'term%'",
          basicExample: "SELECT id FROM products WHERE name LIKE '%phone%';",
          advancedExample: "SELECT id FROM products WHERE name ILIKE 'phone%';",
          commonMistakes: ["Uzywanie contains search do autocomplete.", "Dodanie zwyklego indeksu z oczekiwaniem, ze naprawi contains search."],
          performanceTips: ["Uzywaj wyszukiwania prefiksowego, gdy UX pozwala.", "Dla contains uzywaj trigramow albo full-text."],
        },
      },
    },
    {
      id: "unsafe-updates",
      slug: "unsafe-updates",
      category: "antipatterns",
      difficulty: "beginner",
      dialects: allDialects,
      relatedTopics: ["transactions", "sql-antipatterns-overview"],
      relatedRules: ["update-without-where", "delete-without-where"],
      translations: {
        en: {
          title: "Unsafe UPDATE and DELETE",
          shortDescription: "Protect destructive write statements with predicates and process.",
          explanation:
            "UPDATE and DELETE without WHERE can change every row. Production workflows should require previews, transactions, backups, or migrations.",
          syntax: "UPDATE table SET ... WHERE key = value",
          basicExample: "DELETE FROM sessions WHERE expires_at < NOW();",
          advancedExample: "BEGIN;\nSELECT COUNT(*) FROM sessions WHERE expires_at < NOW();\nDELETE FROM sessions WHERE expires_at < NOW();\nCOMMIT;",
          commonMistakes: ["Running DELETE FROM table during manual maintenance.", "Forgetting tenant filters in multi-tenant systems."],
          performanceTips: ["Batch very large deletes.", "Index cleanup predicates."],
        },
        pl: {
          title: "Niebezpieczne UPDATE i DELETE",
          shortDescription: "Chron destrukcyjne zapisy predykatami i procesem.",
          explanation:
            "UPDATE i DELETE bez WHERE moga zmienic wszystkie wiersze. Produkcja powinna wymagac podgladu, transakcji, backupow lub migracji.",
          syntax: "UPDATE tabela SET ... WHERE klucz = wartosc",
          basicExample: "DELETE FROM sessions WHERE expires_at < NOW();",
          advancedExample: "BEGIN;\nSELECT COUNT(*) FROM sessions WHERE expires_at < NOW();\nDELETE FROM sessions WHERE expires_at < NOW();\nCOMMIT;",
          commonMistakes: ["Uruchamianie DELETE FROM table podczas recznego utrzymania.", "Pomijanie filtra tenant w systemach multi-tenant."],
          performanceTips: ["Batchuj bardzo duze DELETE.", "Indeksuj predykaty czyszczenia."],
        },
      },
    },
    {
      id: "schema-design-basics",
      slug: "schema-design-basics",
      category: "basics",
      difficulty: "beginner",
      dialects: allDialects,
      relatedTopics: ["constraints", "foreign-keys"],
      relatedRules: [],
      translations: {
        en: {
          title: "Schema design basics",
          shortDescription: "Model data so queries and constraints stay simple.",
          explanation:
            "Good schema design keeps facts in the right tables, avoids repeated lists in strings, and gives the database enough structure to enforce rules.",
          syntax: "Entity tables + relationship tables + constraints",
          basicExample: "CREATE TABLE tags (id BIGINT PRIMARY KEY, name TEXT UNIQUE);",
          advancedExample: "CREATE TABLE article_tags (article_id BIGINT REFERENCES articles(id), tag_id BIGINT REFERENCES tags(id), PRIMARY KEY (article_id, tag_id));",
          commonMistakes: ["Storing comma-separated ids in one column.", "Skipping constraints until later."],
          performanceTips: ["Normalize relationships that need filtering.", "Index relationship table foreign keys."],
        },
        pl: {
          title: "Podstawy projektowania schematu",
          shortDescription: "Modeluj dane tak, aby zapytania i constraints byly proste.",
          explanation:
            "Dobry schemat trzyma fakty we wlasciwych tabelach, unika list w stringach i daje bazie strukture do wymuszania regul.",
          syntax: "Tabele encji + tabele relacji + constraints",
          basicExample: "CREATE TABLE tags (id BIGINT PRIMARY KEY, name TEXT UNIQUE);",
          advancedExample: "CREATE TABLE article_tags (article_id BIGINT REFERENCES articles(id), tag_id BIGINT REFERENCES tags(id), PRIMARY KEY (article_id, tag_id));",
          commonMistakes: ["Przechowywanie list id oddzielonych przecinkami.", "Okladanie constraints na pozniej."],
          performanceTips: ["Normalizuj relacje, po ktorych filtrujesz.", "Indeksuj klucze obce tabel relacyjnych."],
        },
      },
    },
    {
      id: "json-querying",
      slug: "json-querying",
      category: "dialects",
      difficulty: "advanced",
      dialects: ["postgresql", "mysql", "oracle", "sqlite", "sqlserver"],
      relatedTopics: ["dialect-differences", "functional-indexes"],
      relatedRules: [],
      translations: {
        en: {
          title: "JSON field access",
          shortDescription: "Query semi-structured data with dialect-specific syntax.",
          explanation:
            "JSON support is powerful but differs widely. Generated columns, expression indexes, or specialized JSON indexes may be needed for performance.",
          syntax: "PostgreSQL: data ->> 'key'\nMySQL: JSON_EXTRACT(data, '$.key')",
          basicExample: "SELECT data ->> 'email' AS email FROM events;",
          advancedExample: "CREATE INDEX idx_events_email ON events ((data ->> 'email'));",
          commonMistakes: ["Treating JSON as a replacement for every relational structure.", "Filtering JSON without a supporting index."],
          performanceTips: ["Promote frequently filtered fields to columns when appropriate.", "Use dialect-specific JSON index options."],
        },
        pl: {
          title: "Dostep do pol JSON",
          shortDescription: "Odpytuj polustrukturalne dane skladnia konkretnego dialektu.",
          explanation:
            "Wsparcie JSON jest mocne, ale bardzo rozne. Dla wydajnosci potrzebne bywaja kolumny generowane, indeksy wyrazeniowe lub indeksy JSON.",
          syntax: "PostgreSQL: data ->> 'key'\nMySQL: JSON_EXTRACT(data, '$.key')",
          basicExample: "SELECT data ->> 'email' AS email FROM events;",
          advancedExample: "CREATE INDEX idx_events_email ON events ((data ->> 'email'));",
          commonMistakes: ["Traktowanie JSON jako zamiennika kazdej struktury relacyjnej.", "Filtrowanie JSON bez wspierajacego indeksu."],
          performanceTips: ["Promuj czesto filtrowane pola do kolumn, gdy ma to sens.", "Uzywaj opcji indeksow JSON danego dialektu."],
        },
      },
    },
  ]);

export const knowledgeTopics = parsedKnowledgeTopics as KnowledgeTopic[];
